### ISSUE TITLE
请问在5.4.1版本中是否实现了坚果云备份的是文件？

### ISSUE THREAD

**Issue by baixiaoyu2997** [PureWriter/resources#12]
之前曾经买过一次高级版，但是跟我预想的不太一样 我需要的是在坚果云中保存的是实体的md文件，但是我在云上看到的貌似更像是配置文件，这个我预想的不太一样 ，后来我就退了，不知道这个版本是否支持这个功能，如果能保存为md文件的话，可以在PC端，移动端无缝切换使用那就太好了。

**Comment by drakeet** [comment]
纯纯写作最新版 9.0.0，这里不提供反馈服务。
